version: '3.8'

services:
  jupyter-notebook:
    build: ./notebook_docker
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/app/notebooks

  flask-backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data/models:/app/models
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/analyticsdb
      - DELETE_MONGO_PASSWORD=deletemongo
    command: flask run --host=0.0.0.0
    networks:
      - backend
    depends_on:
      - mongo

  react-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev:watch"]
    networks:
      - backend
    depends_on:
      - flask-backend

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-frontend
    networks:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./data/db/mongo:/data/db
    networks:
      - backend

# volumes:

networks:
  backend:
    driver: bridge
